server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: yupi
    secret-key: abcdefgh
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.134.227:3306/zapi
    username: zapi
    password: 200279zwh